### ISSUE TITLE
运行flask init错误这个是不是github的key 和secret

### ISSUE THREAD

**Issue by tianke0711** [weijiang1994/university-bbs#18]
flask init
Traceback (most recent call last):
  File "/opt/anaconda3/bin/flask", line 10, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/opt/anaconda3/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1254, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/opt/anaconda3/lib/python3.8/site-packages/click/core.py", line 1297, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/opt/anaconda3/lib/python3.8/site-packages/flask/cli.py", line 542, in get_command
    rv = info.load_app().cli.get_command(ctx, name)
  File "/opt/anaconda3/lib/python3.8/site-packages/flask/cli.py", line 388, in load_app
    app = locate_app(self, import_name, name)
  File "/opt/anaconda3/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/Users/ketian/PycharmProjects/university-bbs/bbs/__init__.py", line 22, in <module>
    from bbs.blueprint.oauth import oauth_bp
  File "/Users/ketian/PycharmProjects/university-bbs/bbs/blueprint/oauth.py", line 59, in <module>
    oschina = oauth.remote_app(
  File "/opt/anaconda3/lib/python3.8/site-packages/flask_oauthlib/client.py", line 78, in remote_app
    remote = OAuthRemoteApp(self, name, **kwargs)
  File "/opt/anaconda3/lib/python3.8/site-packages/flask_oauthlib/client.py", line 284, in __init__
    raise TypeError(
TypeError: OAuthRemoteApp requires consumer key and secret

**Comment by tianke0711** [comment]
ok 啦搞定了

**Comment by weijiang1994** [comment]
> ok 啦搞定了

👍
