### ISSUE TITLE
关于项目实际使用的问题

### ISSUE THREAD

**Issue by GXL911** [weijiang1994/university-bbs#23]
在运行项目时候，用超级管理员权限发帖子，但是发现帖子都是在审核状态，然后邮箱收到邮件，说帖子的内容，让我点击链接审核，但是没有看到有链接，可以让我对这个帖子进行管理，我应该怎么去做这个呢？

**Comment by weijiang1994** [comment]
后台管理用的前后端分离了，具体代码在这两个仓库[管理前端](https://github.com/weijiang1994/bbs-admin-frontend) [管理后端](https://github.com/weijiang1994/bbs-admin-backend)
方便的话，可帮我点个 :star2:

**Comment by GXL911** [comment]
所以如果我要把整个项目都运行起来，要把这个三个responsity 的文件全部运行起来是吗？（已经点了star，感谢大佬的付出

**Comment by weijiang1994** [comment]
> 所以如果我要把整个项目都运行起来，要把这个三个responsity 的文件全部运行起来是吗？（已经点了star，感谢大佬的付出

是的 这个仓库只是用户端，后台需要跑另外两个仓库的代码。

**Comment by weijiang1994** [comment]
其实后台可以在这个项目写接口，当时为了项目结构清晰，所以分开了。

**Comment by GXL911** [comment]
Traceback (most recent call last):
  File "/home/gu/.local/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/gu/.local/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
    response = self.handle_exception(e)
  File "/home/gu/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/gu/.local/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/gu/.local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/gu/.local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/gu/university-bbs/bbs/decorators.py", line 101, in statistic
    return func(*args, **kwargs)
  File "/home/gu/university-bbs/bbs/blueprint/index.py", line 190, in index
    return render_template('frontend/index/index.html',
  File "/home/gu/.local/lib/python3.8/site-packages/flask/templating.py", line 146, in render_template
    ctx.app.update_template_context(context)
  File "/home/gu/.local/lib/python3.8/site-packages/flask/app.py", line 756, in update_template_context
    context.update(func())
  File "/home/gu/university-bbs/bbs/utils.py", line 207, in get_backend_url
    yl = yaml.load(open(os.path.join(basedir, 'conf/config.yml')))
TypeError: load() missing 1 required positional argument: 'Loader'


我将那两个项目按照read.me 的步骤做了，但是在运行后两个程序的时候，运行forntend这个前端项目只能出现一个页面，无法登录，然后是后端这个进去以后就是404，后面我尝试将客户端的项目运行起来，发现上面的报错.

**Comment by weijiang1994** [comment]
这个报错是你pyyaml的版本高了，你需要在load函数里面传入Loader参数。

**Comment by weijiang1994** [comment]
后台管理前端登录账号就是你的客户端的管理员账号。
