### ISSUE TITLE
你好 老哥又遇到个问题在新建帖子后 点击发布出现TypeError: cannot unpack non-iterable NoneType object然后最后是能发布出来的

### ISSUE THREAD

**Issue by lone0x0** [weijiang1994/university-bbs#5]
![截屏2022-02-23 14 43 53](https://user-images.githubusercontent.com/78702504/155272399-74a441b8-a355-4667-aaaa-711e80d3297b.png)

**Comment by weijiang1994** [comment]
错误截图截完整一点

**Comment by lone0x0** [comment]
> 错误截图截完整一点

127.0.0.1 - - [23/Feb/2022 14:41:35] "POST /post/new/ HTTP/1.1" 302 -
send: 'ehlo [127.0.0.1]\r\n'
127.0.0.1 - - [23/Feb/2022 14:41:35] "GET /post/read/3/ HTTP/1.1" 200 -
reply: b'250-newxmesmtplogicsvrszc11.qq.com\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-SIZE 73400320\r\n'
reply: b'250-AUTH LOGIN PLAIN XOAUTH XOAUTH2\r\n'
reply: b'250-AUTH=LOGIN\r\n'
reply: b'250-MAILCOMPRESS\r\n'
reply: b'250 8BITMIME\r\n'
reply: retcode (250); Msg: b'newxmesmtplogicsvrszc11.qq.com\nPIPELINING\nSIZE 73400320\nAUTH LOGIN PLAIN XOAUTH XOAUTH2\nAUTH=LOGIN\nMAILCOMPRESS\n8BITMIME'
send: 'AUTH PLAIN ADE2NTA2NzcxMzdAcXEuY29tAGh2bGtrYW1rbmppbmNhY2E=\r\n'
reply: b'235 Authentication successful\r\n'
reply: retcode (235); Msg: b'Authentication successful'
send: 'quit\r\n'
reply: b'221 Bye.\r\n'
reply: retcode (221); Msg: b'Bye.'
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lone0x0/university-bbs/bbs/email.py", line 10, in async_send_mail
    mail.send(msg)
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 189, in send
    list(sanitize_addresses(message.send_to)),
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 125, in <lambda>
    return map(lambda e: sanitize_address(e, encoding), addresses)
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
TypeError: cannot unpack non-iterable NoneType object

**Comment by lone0x0** [comment]
难道是我python版本的问题？

**Comment by weijiang1994** [comment]
重新安装一下`flask-mail`试一下看~

**Comment by lone0x0** [comment]
> 重新安装一下`flask-mail`试一下看~

可以发布出来 但是会报错
127.0.0.1 - - [23/Feb/2022 15:32:25] "POST /post/new/ HTTP/1.1" 302 -
127.0.0.1 - - [23/Feb/2022 15:32:25] "GET /post/read/5/ HTTP/1.1" 200 -
send: 'ehlo 10.1.168.192.in-addr.arpa\r\n'
reply: b'250-newxmesmtplogicsvrszc8.qq.com\r\n'
reply: b'250-PIPELINING\r\n'
reply: b'250-SIZE 73400320\r\n'
reply: b'250-AUTH LOGIN PLAIN XOAUTH XOAUTH2\r\n'
reply: b'250-AUTH=LOGIN\r\n'
reply: b'250-MAILCOMPRESS\r\n'
reply: b'250 8BITMIME\r\n'
reply: retcode (250); Msg: b'newxmesmtplogicsvrszc8.qq.com\nPIPELINING\nSIZE 73400320\nAUTH LOGIN PLAIN XOAUTH XOAUTH2\nAUTH=LOGIN\nMAILCOMPRESS\n8BITMIME'
send: 'AUTH PLAIN ADE2NTA2NzcxMzdAcXEuY29tAGh2bGtrYW1rbmppbmNhY2E=\r\n'
reply: b'235 Authentication successful\r\n'
reply: retcode (235); Msg: b'Authentication successful'
send: 'quit\r\n'
reply: b'221 Bye.\r\n'
reply: retcode (221); Msg: b'Bye.'
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/lone0x0/university-bbs/bbs/email.py", line 10, in async_send_mail
    mail.send(msg)
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 492, in send
    message.send(connection)
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 427, in send
    connection.send(self)
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 189, in send
    list(sanitize_addresses(message.send_to)),
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 125, in <lambda>
    return map(lambda e: sanitize_address(e, encoding), addresses)
  File "/Users/lone0x0/venv/lib/python3.8/site-packages/flask_mail.py", line 105, in sanitize_address
    nm, addr = addr
TypeError: cannot unpack non-iterable NoneType object
![截屏2022-02-23 15 32 40](https://user-images.githubusercontent.com/78702504/155277528-35f5b088-6791-4072-ab7e-14e1bad41406.png)

**Comment by weijiang1994** [comment]
邮件是通过多线程异步发送的，所以你的帖子能够正常发布，邮件报错，看看是不是你邮箱配置出错了？

**Comment by lone0x0** [comment]
> 邮件是通过多线程异步发送的，所以你的帖子能够正常发布，邮件报错，看看是不是你邮箱配置出错了？
我邮件是这么配置的 老哥可以看看
![截屏2022-02-23 17 08 59](https://user-images.githubusercontent.com/78702504/155289415-2ab09300-12f8-45a7-a1be-d22b6405350e.png)

**Comment by lone0x0** [comment]
然后这么配置也能正常发送邮件

**Comment by lone0x0** [comment]
> > 邮件是通过多线程异步发送的，所以你的帖子能够正常发布，邮件报错，看看是不是你邮箱配置出错了？
> > 我邮件是这么配置的 老哥可以看看
> > ![截屏2022-02-23 17 08 59](https://user-images.githubusercontent.com/78702504/155289415-2ab09300-12f8-45a7-a1be-d22b6405350e.png)

然后这么配置也能发送邮件

**Comment by weijiang1994** [comment]
把邮箱地址加个引号试一下~

**Comment by weijiang1994** [comment]
我知道原因了，在`conf/config.yml`文件中，把`mail`字段设置一下
![image](https://user-images.githubusercontent.com/53400477/155292176-302a1cca-9636-444c-b921-72e6a1781711.png)

**Comment by lone0x0** [comment]
> 我知道原因了，在`conf/config.yml`文件中，把`mail`字段设置一下 ![image](https://user-images.githubusercontent.com/53400477/155292176-302a1cca-9636-444c-b921-72e6a1781711.png)

OK 改了这个就没问题了
